### PR TITLE
Bugfix/dendro bug

### PR DESCRIPTION
**Pull request by Weiqi97**

### CODE REVIEW

**Comment by Weiqi97** [comment]
@chantisnake Yeah... I wasn't sure if removing all shared project configurations is a good idea.. Also do you believe I successfully made pullapprove go away?

**Comment by chantisnake** [comment]
I have delete this project from pull approve. However, it seems like github is still confused...

**Comment by chantisnake** [comment]
I recommend to rethink deleting all the code style setting. I agree we should delete the interoperator setting, since they are platform specific.

**Comment by chantisnake** [comment]
Also, I recommend you to rename the branch and the name of the pull request for easier future reference,

**Comment by chantisnake** [comment]
@Weiqi97 I find there is a reference stating that all the admin can add/remove repo from pullapprove.

https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Pull request closed without merging**
