### PR TITLE
active docs count when uploading wrong filetype

### PR DESCRIPTION
**Pull request by jacksonjreed**
fix for #806

### CODE REVIEW

**Comment by chantisnake** [comment]
Maybe a better way is to "always" query the backend for number of active document, to make sure the backend and the frontend are consistent?

**Comment by jacksonjreed** [comment]
> Maybe a better way is to "always" query the backend for number of active document, to make sure the backend and the frontend are consistent?

hoping to do something like that in fixing #862--this is more of a temporary fix to close the original issue.

**Comment by chantisnake** [comment]
I thought we have talked about the option to always query the backend on how many files do you have?

**Comment by jacksonjreed** [comment]
@chantisnake my plan was to do another pr to add that behavior more consistently across a few pages--however with the front end rewrite most of this stuff will get replace anyway.

**Comment by chantisnake** [comment]
Good! I am glad

**Pull request merged**
