### PR TITLE
Feature/content analysis test suite

### PR DESCRIPTION
**Pull request by Krissac**
updated test suite example

### CODE REVIEW

**Comment by Weiqi97** [comment]
@Landaluce If you have time, could you please take a look at this PR and give it a try to update it? Thank you very much.

**Comment by chantisnake** [comment]
The phrase definition seems weird to me, since it hard codes ascii spaces and newlines etc, which is typically not that good of a idea.

**Comment by chantisnake** [comment]
The phrase definition seems weird to me, since it hard codes ascii spaces and newlines etc, which is typically not that good of a idea.

I don't know if these are really necessary.

**Comment by Weiqi97** [comment]
We addressed some issues presented here in #875 instead.

**Pull request closed without merging**
