### PR TITLE
Re-implements topic cloud handling

### PR DESCRIPTION
**Pull request by scottkleinman**
Fixes some bugs in multicloud that using the re-factored file structure.

### CODE REVIEW

**Comment by chantisnake** [comment]
Do we want this in current master?

**Comment by scottkleinman** [comment]
I think it's OK because the changed function is moved out of `lexos.py`. The other changes shouldn't cause any merge conflicts.

**Comment by chantisnake** [comment]
There are couple of error given by CI:
```
./lexos/interfaces/multi_cloud_interface.py:93:9: N806 variable in function should be lowercase
./lexos/interfaces/multi_cloud_interface.py:93:48: F821 undefined name 'fileManager'
./lexos/interfaces/multi_cloud_interface.py:131:80: E501 line too long (80 > 79 characters)
./lexos/interfaces/multi_cloud_interface.py:143:80: E501 line too long (82 > 79 characters)
```

**Comment by chantisnake** [comment]
all of the above standard is enforced by PEP8 standards,

see the https://github.com/WheatonCS/Lexos/wiki/Python-Coding-Style-Guide for detail

**Comment by chantisnake** [comment]
you can directly push on your branch, this pull request will automatically be updated

**Comment by scottkleinman** [comment]
OK, that should be fixed.

**Comment by chantisnake** [comment]
There are still lines too long...

**Comment by scottkleinman** [comment]
Grrr... My editor's word wrap lied to me. Hopefully the latest fix will pass.

**Comment by chantisnake** [comment]
Lol, this is embarrassing...

**Comment by scottkleinman** [comment]
Are there further errors, or are we just waiting for the CI tests to re-run? I can't tell?

**Comment by chantisnake** [comment]
It is the line too long again... I think.

**Comment by scottkleinman** [comment]
I had to debug it from the command line in the end. Grrrr....

**Pull request merged**
